# This file was generated by GoReleaser. DO NOT EDIT.
cask "md2" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "fef91f36bc5649f832877549bfb58be05c68f833cfd04fbe5cd46fc44d2e1372"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f08c511e79543050f60b91545102928edad2cd770c618866c7755fa1b2c00c1"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cea65bd3b0be91cd21757cd884e1e6105ab09c9d19377ba5025a0b24a84074f8"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "437c7b9bb46ad4dbdef7eb8022270f048174ff4661dd0d359aa382b70e07a1c9"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md2"
  desc "Convert markdown files to PDF, HTML, and text"
  homepage "https://github.com/rapatao/md2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md2"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md2"]
    end
  end

  # No zap stanza required

end
