# This file was generated by GoReleaser. DO NOT EDIT.
cask "md2" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "1dd64b1684d3d91b95a023f64a72834731e762e2e4d8132e624e26b28cca4db8"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "791222b85a546dc4e1a9543b9d71e6fc7acdc6cf4a8ba776b074eefaa2e21237"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2de3d078b365373b0bcf829e982002f560d87cdc0558c32c550250400ca33cb7"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a086aca4970f41937a9de0027ae6f70d07e3256a21b43eb181a2e19add33e6d3"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md2"
  desc "Convert markdown files to PDF, HTML, and text"
  homepage "https://github.com/rapatao/md2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md2"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md2"]
    end
  end

  # No zap stanza required

end
