# This file was generated by GoReleaser. DO NOT EDIT.
cask "md2" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "c040e0e1d3168b5d78e32f084a30c062d7152d883053ec941f0bc20763435984"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "234369f5828c3a9101c37ee31bb2aeebf6193f31da38617315b74b0588106140"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "919dc3b5543077d9e811441203ecdcd58dacd565fbb1d7522c26e85680616d6f"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9239717e8a9252c63401e3ba6a96ea5e1b8957f09e74f41f223044dc6873f301"
      url "https://github.com/rapatao/md2/releases/download/v#{version}/md2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md2"
  desc "Convert markdown files to PDF, HTML, and text"
  homepage "https://github.com/rapatao/md2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md2"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md2"]
    end
  end

  # No zap stanza required

end
