# This file was generated by the virtual-display release workflow. DO NOT EDIT.
cask "virtual-display" do
  version "0.4.0"
  sha256 "61bbff4cc2a5869ed74bd32d58d67767fa6a6d10d21ca88fd646e5614f1e5adf"

  url "https://github.com/rapatao/virtual-display/releases/download/v#{version}/VirtualDisplay.zip"
  name "Virtual Display"
  desc "Mirror a resizable screen region into a shareable window"
  homepage "https://github.com/rapatao/virtual-display"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: ">= :sonoma"

  app "VirtualDisplay.app"

  # The app is not notarized, so macOS quarantines the downloaded bundle and
  # Gatekeeper refuses to open it. Clearing the flag is what makes it launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/VirtualDisplay.app"]
    end
  end

  zap trash: [
    "~/Library/Preferences/com.rapatao.virtual-display.plist",
    "~/Library/Saved Application State/com.rapatao.virtual-display.savedState",
  ]
end
