# This file was generated by the virtual-display release workflow. DO NOT EDIT.
cask "virtual-display" do
  version "0.0.5"
  sha256 "64a334257969cc061aaa31bbb75c0d77a0ca8c0ca82f8f271e4071806b423346"

  url "https://github.com/rapatao/virtual-display/releases/download/v#{version}/VirtualDisplay.zip"
  name "Virtual Display"
  desc "Mirror a resizable screen region into a shareable window"
  homepage "https://github.com/rapatao/virtual-display"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: ">= :sonoma"

  app "VirtualDisplay.app"

  # The app is not notarized, so macOS quarantines the downloaded bundle and
  # Gatekeeper refuses to open it. Clearing the flag is what makes it launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/VirtualDisplay.app"]
    end
  end

  zap trash: [
    "~/Library/Preferences/com.rapatao.virtual-display.plist",
    "~/Library/Saved Application State/com.rapatao.virtual-display.savedState",
  ]
end
